sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t6kVNJ2eTeSbnTqSWyx
    access-key-secret: GLhSjpqdgRN2pZw9iekbYtW9uzf6RD
    bucket-name: web-tilas-wind

  redis:
    host: localhost
    port: 6379
    database: 2